language: python
python: 3.7
dist: xenial
sudo: true

install:
  - pip install setuptools twine

script:
  - python setup.py build
  - python setup.py sdist
  - twine upload dist/* --username $PYPI_USER --password $PYPI_PASS